apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-postgres
  template:
    metadata:
      labels:
        app: payroll-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "payrolldb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc