name: Checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write # needed to upload SARIF

jobs:
  checkstyle:
    name: Checkstyle Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # Add caching for faster builds

      - name: Build project (skip tests)
        run: mvn clean install -DskipTests

#      - name: Combine SARIF reports with JQ
#        id: combine_sarif # Give this step an ID to reference its output
#        run: |
#          # Ensure jq is installed (usually pre-installed, but good to be sure)
#          sudo apt-get update && sudo apt-get install -y jq || true
#
#          # Find all individual SARIF files and concatenate their content.
#          # Then, use jq to slurp all inputs as an array, extract all 'runs' arrays,
#          # flatten them, and reconstruct a single SARIF file.
#          find . -name "checkstyle-result.sarif" -print0 | xargs -0 cat | \
#          jq -s '
#            {
#              "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
#              "version": "2.1.0",
#              "runs": (map(.runs[]) | unique) # map(.runs[]) flattens all 'runs' arrays. unique removes duplicates if any.
#            }
#          ' > combined-checkstyle-result.sarif
#
#          # Check if the combined file was created and is not empty
#          if [ ! -s combined-checkstyle-result.sarif ]; then
#            echo "Warning: Combined SARIF file is empty or not created. Checkstyle might not have found any issues, or there was a jq error."
#            echo "{ \"$schema\": \"https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json\", \"version\": \"2.1.0\", \"runs\": [] }" > combined-checkstyle-result.sarif
#          fi
#
#          echo "Combined SARIF file created at: combined-checkstyle-result.sarif"
#          echo "combined_sarif_path=combined-checkstyle-result.sarif" >> $GITHUB_OUTPUT
#
#      - name: Upload combined SARIF to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          # Now, provide the single combined SARIF file
#          sarif_file: ${{ steps.combine_sarif.outputs.combined_sarif_path }}